//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaEnVivo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class academiaenvivoEntities : DbContext
    {
        public academiaenvivoEntities()
            : base("name=academiaenvivoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaCurso> CategoriaCurso { get; set; }
        public virtual DbSet<Invitado> Invitado { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
    }
}
