//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaEnVivo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Invitado = new HashSet<Invitado>();
        }
    
        public System.Guid id_evento { get; set; }
        public Nullable<System.Guid> id_categoria { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public System.DateTime hora_desde { get; set; }
        public System.DateTime hora_hasta { get; set; }
        public int duracion { get; set; }
        public double precio { get; set; }
        public string invitados { get; set; }
        public bool estado { get; set; }
        public Nullable<System.DateTime> fecha_creado { get; set; }
    
        public virtual CategoriaCurso CategoriaCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitado> Invitado { get; set; }
    }
}
