//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaEnVivo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitado
    {
        public System.Guid id_invitado { get; set; }
        public System.Guid id_evento { get; set; }
        public string email { get; set; }
        public bool asistio { get; set; }
        public string ip { get; set; }
        public Nullable<System.Guid> codigo_asistencia { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
